#!/usr/bin/env python3
"""Apply em dash policy to Article 1 draft. Longest phrases first."""

from pathlib import Path

DRAFT = Path(__file__).resolve().parents[1] / "docs" / "article-1-assembled-draft-v1.md"

# Curated replacements (longest first). Section headers in markdown use colon instead of em dash.
REPLACEMENTS = [
    ("# Article 1 — Assembled Draft (Sections 1–13)", "# Article 1: Assembled Draft (Sections 1–13)"),
    ("## Section 1 — The prescription on the counter", "## Section 1: The prescription on the counter"),
    ("## Section 2 — Not one thing", "## Section 2: Not one thing"),
    ("## Section 3 — The prescribing landscape", "## Section 3: The prescribing landscape"),
    ("## Section 4 — Placing the prescription on the map", "## Section 4: Placing the prescription on the map"),
    ("## Section 5 — Four levels of claim", "## Section 5: Four levels of claim"),
    ("## Section 6 — Commonly prescribed ≠ most studied", "## Section 6: Commonly prescribed ≠ most studied"),
    ("## Section 7 — Athreya Sugar Relief", "## Section 7: Athreya Sugar Relief"),
    ("## Section 8 — Harmony Amla & Beyond (Nishamalaki)", "## Section 8: Harmony Amla & Beyond (Nishamalaki)"),
    ("## Section 9 — The four ingredients", "## Section 9: The four ingredients"),
    ("## Section 10 — Prostate and urinary products", "## Section 10: Prostate and urinary products"),
    ("## Section 11 — Safety and complexity", "## Section 11: Safety and complexity"),
    ("## Section 12 — What each layer can claim", "## Section 12: What each layer can claim"),
    ("## Section 13 — What I would ask now", "## Section 13: What I would ask now"),
    ("**Athreya Sugar Relief** — marketed", "**Athreya Sugar Relief:** marketed"),
    ("**Harmony Nutraceuticals Amla & Beyond** — a modern", "**Harmony Nutraceuticals Amla & Beyond:** a modern"),
    ("**ChandraPrabha Vati** — a classical", "**ChandraPrabha Vati:** a classical"),
    ("**Kerala Ayurveda Prostate Care** — another", "**Kerala Ayurveda Prostate Care:** another"),
    ("when they are being used to address the same conditions I will encounter in patients — elevated glucose, elevated triglycerides, the metabolic patterns dietitians see every day.",
     "when they are being used to address the same conditions I will encounter in patients: elevated glucose, elevated triglycerides, and the metabolic patterns dietitians see every day."),
    ("commonly prescribe for metabolic disease — across government guidelines, clinical training, and the commercial market.",
     "commonly prescribe for metabolic disease, across government guidelines, clinical training, and the commercial market."),
    ("Coherence is not the same as proof — but I did not yet know how far apart those two things would turn out to be.",
     "Coherence is not the same as proof. I did not yet know how far apart those two things would turn out to be."),
    ("Dietary rules come first in official guidelines — what to eat, what to avoid, when to eat it.",
     "Dietary rules come first in official guidelines: what to eat, what to avoid, when to eat it."),
    ("Ayurvedic metabolic care has its own disease categories — Prameha and Madhumeha on the glucose side, Medoroga on the lipid side — but in practice they overlap constantly.",
     "Ayurvedic metabolic care has its own disease categories (Prameha and Madhumeha on the glucose side, Medoroga on the lipid side), but in practice they overlap constantly."),
    ("Different formulations, different brands, different forms — churna versus capsule, classical kwatha versus OTC juice.",
     "Different formulations, different brands, different forms (churna versus capsule, classical kwatha versus OTC juice)."),
    ("This investigation focuses on those bottles — the therapies with names on the label — not on the full Ayurvedic care plan they may have been embedded in.",
     "This investigation focuses on those bottles, the therapies with names on the label, not on the full Ayurvedic care plan they may have been embedded in."),
    ("that begins with Nishamalaki — turmeric and amla together — alongside classical decoctions",
     "that begins with Nishamalaki (turmeric and amla together), alongside classical decoctions"),
    ("looks different in form — more capsules, more juices, more branded multi-herb products — but not in what goes into them.",
     "looks different in form (more capsules, more juices, more branded multi-herb products) but not in what goes into them."),
    ("and guggulu resin — the base for dozens of compound tablets.",
     "and guggulu resin, the base for dozens of compound tablets."),
    ("built from that core basket — not a single isolated herb in most cases.",
     "built from that core basket, not a single isolated herb in most cases."),
    ("in the landscape — the same ones that appear in government lists",
     "in the landscape, the same ones that appear in government lists"),
    ("of Nishamalaki — also called Nisa Amalaki — the classical pairing",
     "of Nishamalaki, also called Nisa Amalaki, the classical pairing"),
    ("with dozens of ingredients — guggulu, shilajit, triphala, daruharidra, and mineral preparations",
     "with dozens of ingredients: guggulu, shilajit, triphala, daruharidra, and mineral preparations"),
    ("**Kerala Ayurveda Prostate Care** — marketed as Prostact — combines",
     "**Kerala Ayurveda Prostate Care** (marketed as Prostact) combines"),
    ("urinary frequency, and flow — not blood sugar or triglycerides directly.",
     "urinary frequency, and flow, not blood sugar or triglycerides directly."),
    ("The overlap was immediate — on the prescribing side, at least.",
     "The overlap was immediate on the prescribing side, at least."),
    ("Everything looked institutionally recognizable — the kind of prescription a landscape review would predict",
     "Everything looked institutionally recognizable, the kind of prescription a landscape review would predict"),
    ("What the literature actually supported — and whether any of it applied to these products — was still ahead of me.",
     "What the literature actually supported, and whether any of it applied to these products, was still ahead of me."),
    ("regularly recommend — the herb basket and classical formulations from the previous section.",
     "regularly recommend: the herb basket and classical formulations from the previous section."),
    ("literature lives here — including studies that never tested the bottles on the counter.",
     "literature lives here, including studies that never tested the bottles on the counter."),
    ("Related ideas — not identical interventions.",
     "Related ideas, not identical interventions."),
    ("for different reasons — prostate and urinary health — though they sat in the same bag",
     "for different reasons (prostate and urinary health), though they sat in the same bag"),
    ("a second problem — one I had not expected when I started with a prescription that looked so well aligned with the prescribing map.",
     "a second problem I had not expected when I started with a prescription that looked so well aligned with the prescribing map."),
    ("Triglycerides — one of the markers on my relative&rsquo;s lab report — showed up far less often",
     "Triglycerides (one of the markers on my relative&rsquo;s lab report) showed up far less often"),
    ("Methi — fenugreek — ranked at the top",
     "Methi (fenugreek) ranked at the top"),
    ("in its main tables — a gap that reflects how fragmented the evidence landscape is",
     "in its main tables, a gap that reflects how fragmented the evidence landscape is"),
    ("prescribed constantly — including in the Amla & Beyond bottle on the counter.",
     "prescribed constantly, including in the Amla & Beyond bottle on the counter."),
    ("at Level 1 — recognizable, coherent, well aligned with what practitioners commonly recommend — while most",
     "at Level 1 (recognizable, coherent, well aligned with what practitioners commonly recommend) while most"),
    ("the metabolic products — the ones aimed directly at blood sugar and triglycerides.",
     "the metabolic products, the ones aimed directly at blood sugar and triglycerides."),
    ("and amla (amalaki) — four of the most common anti-Prameha herbs",
     "and amla (amalaki), four of the most common anti-Prameha herbs"),
    ("of Athreya Sugar Relief — not under that name, not under Athreya Herbs, not testing this four-herb combination at any dose.",
     "of Athreya Sugar Relief: not under that name, not under Athreya Herbs, not testing this four-herb combination at any dose."),
    ("ingredient-level evaluation — with the same non-transfer rule in force.",
     "ingredient-level evaluation, with the same non-transfer rule in force."),
    ("a different category — a classical formulation with government first-line status and a small body of formulation-level research.",
     "a different category: a classical formulation with government first-line status and a small body of formulation-level research."),
    ("**Harmony Amla & Beyond** is a modern version of Nishamalaki — also called Nisa Amalaki — the classical pairing of turmeric and amla that sits in the first line of the Ministry of AYUSH metabolic guidelines.",
     "**Harmony Amla & Beyond** is a modern version of Nishamalaki, also called Nisa Amalaki, the classical pairing of turmeric and amla that sits in the first line of the Ministry of AYUSH metabolic guidelines."),
    ("Amla & Beyond is Harmony Nutraceuticals&rsquo; modern version of Nishamalaki — also called Nisa Amalaki — a classical pairing of turmeric and amla that sits in the first line of the Ministry of AYUSH metabolic treatment guidelines. The classical form is equal parts churna: powdered turmeric and powdered amla mixed together. This product uses a concentrated amla extract (Amlowin&trade;), full-spectrum organic turmeric, and a Triperine&trade; blend of ginger, black pepper, and long pepper intended to improve absorption.",
     "Harmony Nutraceuticals&rsquo; Amla & Beyond belongs to the Nishamalaki class described in the previous section, a modern capsule using concentrated amla extract (Amlowin&trade;), full-spectrum organic turmeric, and a Triperine&trade; bioavailability blend. My question here was narrower: had anyone tested this exact product as a finished metabolic intervention, and what did formulation-level research suggest?"),
    ("on its component herbs — but it is not empty.",
     "on its component herbs, but it is not empty."),
    ("EmbliQur&reg; capsules — a modern amla-turmeric product with a bioavailability enhancer",
     "EmbliQur&reg; capsules, a modern amla-turmeric product with a bioavailability enhancer"),
    ("HbA1c, and HOMA-IR — a measure of insulin resistance.",
     "HbA1c, and HOMA-IR (a measure of insulin resistance)."),
    ("in prediabetes — in a structurally similar product, not in Amla & Beyond itself.",
     "in prediabetes, in a structurally similar product, not in Amla & Beyond itself."),
    ("and worse for BMI — in a small, short, single-blind trial.",
     "and worse for BMI, in a small, short, single-blind trial."),
    ("most of the signal lived — and where most of the confusion came from.",
     "most of the signal lived, and where most of the confusion came from."),
    ("those ingredients — turmeric and amla — were arriving from two directions at once.",
     "those ingredients (turmeric and amla) were arriving from two directions at once."),
    ("classic Pramehaghna — a &ldquo;sugar destroyer&rdquo; — and among the most heavily marketed",
     "classic Pramehaghna, a &ldquo;sugar destroyer,&rdquo; and among the most heavily marketed"),
    ("meta-analyses exist — one pooling ten studies",
     "meta-analyses exist, one pooling ten studies"),
    ("is adjunct use — helpful alongside conventional treatment, not a replacement for it.",
     "is adjunct use, helpful alongside conventional treatment, not a replacement for it."),
    ("Guduchi — *Tinospora cordifolia* — is prescribed",
     "Guduchi (*Tinospora cordifolia*) is prescribed"),
    ("over 60 days — but HbA1c change in that study did not reach statistical significance.",
     "over 60 days, but HbA1c change in that study did not reach statistical significance."),
    ("without significant glycemic change — a useful reminder that not every guduchi-containing regimen moves the numbers.",
     "without significant glycemic change, a useful reminder that not every guduchi-containing regimen moves the numbers."),
    ("Promising but limited — with a safety profile that deserves separate attention.",
     "Promising but limited, with a safety profile that deserves separate attention."),
    ("unless formulated for bioavailability — which is precisely what the Nishamalaki product attempts with Triperine.",
     "unless formulated for bioavailability, which is precisely what the Nishamalaki product attempts with Triperine."),
    ("insulin resistance improvements — often with different curcumin formulations and doses.",
     "insulin resistance improvements, often with different curcumin formulations and doses."),
    ("Amla — *Emblica officinalis*, Indian gooseberry — is the other herb arriving twice.",
     "Amla (*Emblica officinalis*, Indian gooseberry) is the other herb arriving twice."),
    ("at Level 2 — with the same transfer caveats as everything else.",
     "at Level 2, with the same transfer caveats as everything else."),
    ("compared to metformin — open-label designs that require cautious reading.",
     "compared to metformin; open-label designs that require cautious reading."),
    ("at the product level — especially when the patient may be receiving amla from two bottles at unknown cumulative doses.",
     "at the product level, especially when the patient may be receiving amla from two bottles at unknown cumulative doses."),
    ("prostate and urinary health — but they arrived in the same bag",
     "prostate and urinary health, but they arrived in the same bag"),
    ("for metabolic relevance — whether they belong in a conversation about HbA1c and triglycerides.",
     "for metabolic relevance: whether they belong in a conversation about HbA1c and triglycerides."),
    ("herbo-mineral compound — dozens of ingredients including guggulu",
     "herbo-mineral compound with dozens of ingredients including guggulu"),
    ("over 24 weeks — open-label, small, and not a test of the product&rsquo;s value for triglycerides.",
     "over 24 weeks (open-label, small, and not a test of the product&rsquo;s value for triglycerides)."),
    ("than this article attempts — but it is not a risk to wave away.",
     "than this article attempts, but it is not a risk to wave away."),
    ("Prostate Care — marketed as Prostact — combines",
     "Prostate Care (marketed as Prostact) combines"),
    ("fraction of a gram — far below doses used in nutrition research for lipid effects.",
     "fraction of a gram, far below doses used in nutrition research for lipid effects."),
    ("that has not been tested — the same mistake the ladder is meant to prevent.",
     "that has not been tested. That is the same mistake the ladder is meant to prevent."),
    ("as benign — especially when several products overlap and some ingredients carry documented risks.",
     "as benign, especially when several products overlap and some ingredients carry documented risks."),
    ("after starting guduchi — especially alongside other herbs — is worth taking seriously.",
     "after starting guduchi, especially alongside other herbs, is worth taking seriously."),
    ("fractions of a percent — not the magnitude associated with first-line diabetes medications.",
     "fractions of a percent, not the magnitude associated with first-line diabetes medications."),
    ("equally careful — not &ldquo;does it work,&rdquo; but what each layer of this prescription can actually claim.",
     "equally careful: not &ldquo;does it work,&rdquo; but what each layer of this prescription can actually claim."),
    ("**L1 — Commonly prescribed**", "**L1: Commonly prescribed**"),
    ("**L2 — Ingredients**", "**L2: Ingredients**"),
    ("**L3 — Formulations**", "**L3: Formulations**"),
    ("**L4 — Products**", "**L4: Products**"),
    ("investigation produced — not to whether Ayurveda works, but to what kind of claim each layer of this prescription can support.",
     "investigation produced: not whether Ayurveda works, but what kind of claim each layer of this prescription can support."),
    ("individual ingredients — more for some than others, more for glucose than for triglycerides in several cases, and always with dose and design caveats.",
     "individual ingredients, more for some than others, more for glucose than for triglycerides in several cases, and always with dose and design caveats."),
    ("metabolic proprietary products — the ones most directly tied to blood sugar and triglycerides — have no published trials",
     "metabolic proprietary products, the ones most directly tied to blood sugar and triglycerides, have no published trials"),
    ("honest framing is adjunct — something that might help alongside conventional care, with glucose monitoring and attention to liver symptoms — not substitution.",
     "honest framing is adjunct: something that might help alongside conventional care, with glucose monitoring and attention to liver symptoms, not substitution."),
    ("more coherent than I had assumed going in — not random wellness shopping, but herbs and formulation classes",
     "more coherent than I had assumed going in: not random wellness shopping, but herbs and formulation classes"),
    ("gymnema and guduchi — and tilted toward glucose outcomes more than triglycerides.",
     "gymnema and guduchi, and tilted toward glucose outcomes more than triglycerides."),
    ("else are you taking — prescriptions, other supplements, duplicate herbs across multiple bottles?",
     "else are you taking: prescriptions, other supplements, duplicate herbs across multiple bottles?"),
    ("supplement facts label — milligrams per ingredient, extract type, lot number?",
     "supplement facts label: milligrams per ingredient, extract type, lot number?"),
    ("these products — and because future patients will arrive with bags like this one",
     "these products, and because future patients will arrive with bags like this one"),
    ("next layer of questions — labels, doses, manufacturing quality, heavy metals, third-party testing — is a different investigation.",
     "next layer of questions (labels, doses, manufacturing quality, heavy metals, third-party testing) is a different investigation."),
]


def main():
    text = DRAFT.read_text(encoding="utf-8")
    original_count = text.count("—")
    for old, new in REPLACEMENTS:
        if old not in text:
            continue
        text = text.replace(old, new)
    remaining = text.count("—")
    DRAFT.write_text(text, encoding="utf-8")
    print(f"Em dashes: {original_count} -> {remaining}")
    if remaining:
        for i, line in enumerate(text.splitlines(), 1):
            if "—" in line:
                print(f"  L{i}: {line[:100]}...")


if __name__ == "__main__":
    main()
